# Generated by Django 6.0.3 on 2026-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a certified creator.'),
        ),
    ]
