# Generated by Django 6.0.3 on 2026-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', help_text='Filename of the chosen avatar from assets/avatars/.', max_length=200),
        ),
    ]
