# Generated by Django 6.0.3 on 2026-03-22 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('milestone', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IDS',
                'verbose_name_plural': 'IDSs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ifc_version', models.CharField(choices=[('IFC2X3', 'IFC2X3'), ('IFC4', 'IFC4'), ('IFC4X3_ADD2', 'IFC4X3_ADD2')], max_length=20)),
                ('identifier', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('applicability_data', models.JSONField(blank=True, default=dict)),
                ('requirements_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDSSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ids_core.ids')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ids_core.specification')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ids', 'specification')},
            },
        ),
        migrations.AddField(
            model_name='ids',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='ids_parents', through='ids_core.IDSSpecification', to='ids_core.specification'),
        ),
    ]
