# Generated by Django 6.0.3 on 2026-03-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ids',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ids',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
