# Generated by Django 5.2.12 on 2026-03-22 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('use_case', 'Use Case'), ('stage', 'Stage'), ('discipline', 'Discipline'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ids',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ids',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idsspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ids',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idsspecification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ApplicabilityCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entity', 'Entity'), ('property', 'Property'), ('classification', 'Classification'), ('material', 'Material')], max_length=20)),
                ('key', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_conditions', to='ids_core.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_set', models.CharField(blank=True, default='', max_length=255)),
                ('property_name', models.CharField(blank=True, default='', max_length=255)),
                ('constraint_type', models.CharField(choices=[('exists', 'Exists'), ('equals', 'Equals'), ('pattern', 'Pattern')], max_length=20)),
                ('value', models.TextField(blank=True, default='')),
                ('data_type', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ids_core.specification')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_tags', to='ids_core.specification')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_tags', to='ids_core.tag')),
            ],
            options={
                'unique_together': {('specification', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='IDSTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_tags', to='ids_core.ids')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_tags', to='ids_core.tag')),
            ],
            options={
                'unique_together': {('ids', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ids_core.ids')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ids_core.specification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ids'), ('user', 'specification')},
            },
        ),
    ]
