# Generated by Django 6.0.3 on 2026-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_core', '0002_ids_is_deleted_ids_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
