# Generated by Django 6.0.3 on 2026-03-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_core', '0003_alter_applicabilitycondition_id_alter_ids_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='ids_core.ids')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='ids_core.specification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ids__isnull', False), ('specification__isnull', True)), models.Q(('ids__isnull', True), ('specification__isnull', False)), _connector='OR'), name='endorsement_exactly_one_target')],
                'unique_together': {('user', 'ids'), ('user', 'specification')},
            },
        ),
    ]
